cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy

init:
  stage: init
  image: node:14
  script:
    - cd front
    - yarn install

deploy:
  image: node:14
  stage: deploy
  script:
    - git remote add heroku https://heroku:a1121d9d-d418-4597-8b0c-fa46b2f8431c@git.heroku.com/promocode-share.git
    - git subtree push --prefix front heroku master
  only:
    - develop

