version: '3.1'

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=selectel
      - POSTGRES_DB=selectel
    volumes:
      - ./:/app
    ports:
      - ${POSTGRES_PORT:-5432}:5432